version: 2.1

orbs:
  docker: circleci/docker@2.1.4
  heroku: circleci/heroku@2.0.0

jobs:
  deploy:
    docker:
      - image: cimg/eclipse-temurin:17-jdk-jammy
    steps:
      - setup_remote_docker
      - checkout
      - heroku/install
      - run:
          name: Heroku Container Push
          command: |
            heroku container:login
            heroku container:push web -a james-su-devops
            heroku container:release web -a james-su-devops

workflows:
  simple_workflow:
    jobs:
      - deploy
